name: Daily Gold Price and Alert

on:
  schedule:
    - cron: '0 1 * * *'  # Run every day at 6 AM UTC
  workflow_dispatch:

jobs:
  gold-alert:
    runs-on: ubuntu-latest

    env:
      METALPRICE_API_KEY: ${{ secrets.METALPRICE_API_KEY }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch gold price and save CSV
        run: python get_gold_alert.py

      - name: Commit and push updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if [ -f gold_ohlc_per_gram.csv ]; then
            git add gold_ohlc_per_gram.csv
            git diff --quiet && git diff --staged --quiet || git commit -m "Update gold OHLC CSV [$(date -u +'%Y-%m-%d')]"
            git push
          else
            echo "CSV file does not exist; skipping commit."
          fi
      - name: Send Telegram alert
        run: python send_alert.py


