name: Daily Gold Price and Alert

on:
  schedule:
    - cron: '0 1 * * *'  # Run every day at 6 AM UTC
  workflow_dispatch:

jobs:
  gold-alert:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.METALPRICE_API_KEY }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch gold price and save CSV
        run: python get_gold_alert.py

      - name: Send Telegram alert
        run: python send_alert.py
